NotBK/Models/PromoItem.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;
using System.Collections.Generic;

namespace NotBK.Models;

public partial class PromoItem
{
    public string CodItem { get; set; } = null!;

    public string CodPromo { get; set; } = null!;

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    [ValidateNever]
    public virtual Item CodItemNavigation { get; set; } = null!;
    [ValidateNever]
    public virtual Promocion CodPromoNavigation { get; set; } = null!;
}

NotBK/Controllers/PromoItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotBK.Models;

namespace NotBK.Controllers
{
    public class PromoItemsController : Controller
    {
        private readonly NotBkContext _context;

        public PromoItemsController(NotBkContext context)
        {
            _context = context;
        }

        // GET: PromoItems
        public async Task<IActionResult> Index()
        {
            var notBkContext = _context.PromoItems.Include(p => p.CodItemNavigation).Include(p => p.CodPromoNavigation);
            return View(await notBkContext.ToListAsync());
        }

        // GET: PromoItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promoItem = await _context.PromoItems
                .Include(p => p.CodItemNavigation)
                .Include(p => p.CodPromoNavigation)
                .FirstOrDefaultAsync(m => m.CodItem == id);
            if (promoItem == null)
            {
                return NotFound();
            }

            return View(promoItem);
        }

        // GET: PromoItems/Create
        public IActionResult Create()
        {
            ViewBag.CodItem = new SelectList(_context.Items, "CodItem", "Nombre");
            ViewBag.CodPromo = new SelectList(_context.Promocions, "CodPromo", "Nombre");
            return View();
        }

        // POST: PromoItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodItem,CodPromo,FechaInicio,FechaFin")] PromoItem promoItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(promoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CodItem = new SelectList(_context.Items, "CodItem", "Nombre", promoItem.CodItem);
            ViewBag.CodPromo = new SelectList(_context.Promocions, "CodPromo", "Nombre", promoItem.CodPromo);
            return View(promoItem);
        }

        // GET: PromoItems/Edit/5
        public async Task<IActionResult> Edit(string id, string id2)
        {
            if (id == null || id2 == null)
            {
                return NotFound();
            }

            var promoItem = await _context.PromoItems.FindAsync(id, id2);
            if (promoItem == null)
            {
                return NotFound();
            }

            ViewBag.Id = id;
            ViewBag.Id2 = id2;

            ViewData["CodItem"] = new SelectList(_context.Items, "CodItem", "CodItem", promoItem.CodItem);
            ViewData["CodPromo"] = new SelectList(_context.Promocions, "CodPromo", "CodPromo", promoItem.CodPromo);
            return View(promoItem);
        }



        // POST: PromoItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPost(string id, string id2, [Bind("CodItem,CodPromo,FechaInicio,FechaFin")] PromoItem promoItem)
        {
            if (id != promoItem.CodItem || id2 != promoItem.CodPromo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromoItemExists(promoItem.CodItem, promoItem.CodPromo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodItem"] = new SelectList(_context.Items, "CodItem", "CodItem", promoItem.CodItem);
            ViewData["CodPromo"] = new SelectList(_context.Promocions, "CodPromo", "CodPromo", promoItem.CodPromo);
            return View(promoItem);
        }


        // GET: PromoItems/Delete/5
        public async Task<IActionResult> Delete(string id, string id2)
        {
            if (id == null || id2 == null)
            {
                return NotFound();
            }

            var promoItem = await _context.PromoItems
                .Include(p => p.CodItemNavigation)
                .Include(p => p.CodPromoNavigation)
                .FirstOrDefaultAsync(m => m.CodItem == id && m.CodPromo == id2);
            if (promoItem == null)
            {
                return NotFound();
            }

            ViewBag.Id = id;
            ViewBag.Id2 = id2;

            return View(promoItem);
        }

        // POST: PromoItems/DeleteConfirmed
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id, string id2)
        {
            var promoItem = await _context.PromoItems.FindAsync(id, id2);
            if (promoItem != null)
            {
                _context.PromoItems.Remove(promoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
        private bool PromoItemExists(string id)
        {
            return _context.PromoItems.Any(e => e.CodItem == id);
        }

        private bool PromoItemExists(string id, string id2)
        {
            return _context.PromoItems.Any(e => e.CodItem == id) && _context.PromoItems.Any(e => e.CodPromo == id2);
        }
    }
}

NotBK/Views/PromoItems/Create.cshtml
@model NotBK.Models.PromoItem

@{
    ViewData["Title"] = "Create";
}



<h4>Agregar un item a una promoción</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CodItem" class="control-label">Item</label>
                <select asp-for="CodItem" class ="form-control" asp-items="ViewBag.CodItem"></select>
            </div>
            <div class="form-group">
                <label asp-for="CodPromo" class="control-label">Promoción</label>
                <select asp-for="CodPromo" class ="form-control" asp-items="ViewBag.CodPromo"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label">Fecha de inicio</label>
                <input type="date" asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label">Fecha de fin</label>
                <input type="date" asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Confirmar registro" class="btn btn-outline-success" />
            </div>
            

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a los items con promoción</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NotBK/Views/PromoItems/Delete.cshtml
@model NotBK.Models.PromoItem

@{
    ViewData["Title"] = "Delete";
}



<h3>¿Estás seguro que quieres eliminar al item de la promoción?</h3>
<div>
    <h4>Item en promo:</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CodItem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodItem)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CodPromo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodPromo)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed" method="post">
        <input type="hidden" asp-for="CodItem" />
        <input type="hidden" asp-for="CodPromo" />
        <input type="hidden" name="id" value="@ViewBag.Id" />
        <input type="hidden" name="id2" value="@ViewBag.Id2" />
        <input type="submit" value="Confirmar eliminación" class="btn btn-outline-danger" /> |
        <a asp-action="Index">Volver a la lista de items en promoción</a>
    </form>
</div>

NotBK/Views/PromoItems/Details.cshtml
@model NotBK.Models.PromoItem

@{
    ViewData["Title"] = "Details";
}



<div>
    <h4>Item en promoción</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Fecha de inicio
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            Fecha de finalización
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt class="col-sm-2">
            Item
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodItemNavigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            Promoción
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodPromoNavigation.Nombre)
        </dd>

        <dt class = "col-sm-2">
            Código del item en descuento
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodItemNavigation.CodItem)
        </dd>
        <dt class = "col-sm-2">
            Código de la promoción
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodPromoNavigation.CodPromo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modificar duración del descuento", "Edit", new { id = Model.CodItem, id2 = Model.CodPromo }) |
    <a asp-action="Index">Volver a la lista de items en promoción</a>
</div>

NotBK/Views/PromoItems/Edit.cshtml
@model NotBK.Models.PromoItem

@{
    ViewData["Title"] = "Edit";
}

<h1 style="font-size: 22px" >Modificar la duración</h1>

<h4>Item en promoción</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="PromoItems" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodItem" />
            <input type="hidden" asp-for="CodPromo" />
            <input type="hidden" name="id" value="@ViewBag.Id" />
            <input type="hidden" name="id2" value="@ViewBag.Id2" />
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label">Fecha de inicio</label>
                <input type="date" asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaFin" class="control-label">Fecha de fin</label>
                <input type="date" asp-for="FechaFin" class="form-control" />
                <span asp-validation-for="FechaFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista de items en promoción</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NotBK/Views/PromoItems/Index.cshtml
@model IEnumerable<NotBK.Models.PromoItem>

@{
    ViewData["Title"] = "Index";
}

<h1 style="font-size: 22px" >Items en promoción</h1>

<p>
    <a asp-action="Create">Agregar nuevo item</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Fecha de inicio
            </th>
            <th>
                Último día disponible
            </th>
            <th>
                Item
            </th>
            <th>
                Promoción
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodItemNavigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodPromoNavigation.Nombre)
            </td>
            <td>

                    @Html.ActionLink("Modificar duración del descuento", "Edit", new {  id = item.CodItem, id2 = item.CodPromo }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Revisar detalles", "Details", new { id = item.CodItem, id2 = item.CodPromo }, new { @class = "btn btn-info", @style="color: white" }) |
                    @Html.ActionLink("Disociar un item de una promoción", "Delete", new { id = item.CodItem, id2 = item.CodPromo }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>